baseURL: /
title: Shazixnar's blog
theme: github.com/razonyang/hugo-theme-bootstrap
copyright: 'Copyright © 2023-{year} Shazixnar. All Rights Reserved.'
defaultContentLanguage: zh-hans
hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-76Y0FN1T5S
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  proxy: https://goproxy.cn
